import { useQuery } from '@tanstack/react-query'
import { apiFetch } from '@/api/client'

/**
 * Workspace metadata returned by `GET /api/workspace`. The real type will be
 * generated by ts-rs once ft-ui exposes a `WorkspaceInfo` struct — until then
 * we ship a minimal hand-typed shape so the rest of the app can compile.
 */
export interface WorkspaceInfo {
  root: string
  identity?: string | null
}

export const workspaceQueryKey = ['workspace'] as const

export function useWorkspace() {
  return useQuery({
    queryKey: workspaceQueryKey,
    queryFn: () => apiFetch<WorkspaceInfo>('/api/workspace'),
    staleTime: 30_000,
  })
}
