// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`add_component`].
 */
export type AddComponentInput = { 
/**
 * Component name (unique key in the map).
 */
name: string, 
/**
 * Repo-relative path.
 */
path: string, 
/**
 * Optional one-line summary.
 */
summary: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
