// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One alias → scope-id entry.
 */
export type AliasEntry = { 
/**
 * Alias text.
 */
alias: string, 
/**
 * Scope id the alias resolves to.
 */
scopeId: string, };
