// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewAcRow } from "./ReviewAcRow";
import type { ReviewEvidenceRow } from "./ReviewEvidenceRow";
import type { ReviewHistoryRow } from "./ReviewHistoryRow";

/**
 * Output of [`review`].
 */
export type AuditReviewOutput = { 
/**
 * Canonical id.
 */
id: string, 
/**
 * Lowercased kind.
 */
kind: string, 
/**
 * Title.
 */
title: string, 
/**
 * Status (lowercase).
 */
status: string, 
/**
 * Priority (lowercase).
 */
priority: string, 
/**
 * Current owner identity, if any.
 */
owner: string | null, 
/**
 * Owning scope.
 */
owningScope: string | null, 
/**
 * Creating identity.
 */
createdBy: string, 
/**
 * Creation timestamp (RFC3339).
 */
createdAt: string, 
/**
 * Updated timestamp (RFC3339).
 */
updatedAt: string, 
/**
 * Trust state, for memory kinds.
 */
trustState: string | null, 
/**
 * Risk class, for memory kinds.
 */
riskClass: string | null, 
/**
 * `true` iff the risk class is high-stakes (ADR-0013).
 */
highStakes: boolean, 
/**
 * On-disk state hash.
 */
stateHash: string, 
/**
 * `valid` or `invalid: <reason>`.
 */
chainStatus: string, 
/**
 * Convenience boolean.
 */
chainValid: boolean, 
/**
 * Acceptance criteria.
 */
acceptanceCriteria: Array<ReviewAcRow>, 
/**
 * Attached evidence.
 */
evidence: Array<ReviewEvidenceRow>, 
/**
 * History timeline.
 */
history: Array<ReviewHistoryRow>, 
/**
 * Free-form suggested next action.
 */
suggestedNextAction: string, };
