// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`review`].
 */
export type AuditReviewInput = { 
/**
 * Record id (full canonical or unambiguous prefix).
 */
id: string, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
