// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single card on the board.
 */
export type BoardCard = { 
/**
 * Full canonical id.
 */
id: string, 
/**
 * Short form (first 8 hex chars after the kind tag) for display.
 */
short_id: string, 
/**
 * Title.
 */
title: string, 
/**
 * Record kind, lowercase (`"epic"|"task"|"subtask"|"bug"`). Drives the type pill.
 */
kind: string, 
/**
 * Fine-grained status, lowercase `snake_case` (`"open"`, `"ready"`,
 * `"in_progress"`, `"blocked"`, `"review"`, `"closed"`, `"deferred"`,
 * `"archived"`). The column buckets several statuses together, so consumers
 * that need the exact status (e.g. the backlog table) read this field.
 */
status: string, 
/**
 * Priority (lowercase, e.g. `"p1"`).
 */
priority: string, 
/**
 * Owner identity if set.
 */
owner: string | null, 
/**
 * Canonical id of the enclosing epic, resolved by walking `parent_id`. `None` for orphans/epics.
 */
epic_id: string | null, 
/**
 * Total acceptance criteria attached to this record.
 */
criteria_total: number, 
/**
 * Acceptance criteria with status `checked`.
 */
criteria_met: number, 
/**
 * Direct children of kind `Subtask`.
 */
subtask_count: number, 
/**
 * Count of outgoing `blocked-by` edges.
 */
blocked_by_count: number, };
