// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardCard } from "./BoardCard";

/**
 * Output of [`board`].
 */
export type BoardOutput = { 
/**
 * Tickets in `Open` / `Ready` status.
 */
todo: Array<BoardCard>, 
/**
 * Tickets in `InProgress` / `Blocked` status.
 */
in_progress: Array<BoardCard>, 
/**
 * Tickets in `Review` status.
 */
review: Array<BoardCard>, 
/**
 * Tickets in `Closed` status.
 */
done: Array<BoardCard>, };
