// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`board`].
 */
export type BoardInput = { 
/**
 * Filter by scope.
 */
scope: string | null, 
/**
 * Filter by owner.
 */
owner: string | null, 
/**
 * When `true`, only return unblocked records (delegates to the ready
 * index query). Mirrors the `?ready=true` flag on `/api/tickets`.
 */
ready: boolean, };
