// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single card on the board.
 */
export type BoardCard = { 
/**
 * Full canonical id.
 */
id: string, 
/**
 * Short form (first 8 hex chars after the kind tag) for display.
 */
short_id: string, 
/**
 * Title.
 */
title: string, 
/**
 * Priority (lowercase, e.g. `"p1"`).
 */
priority: string, 
/**
 * Owner identity if set.
 */
owner: string | null, };
