// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A lightweight epic summary included in [`BoardOutput`].
 */
export type BoardEpic = { 
/**
 * Full canonical id.
 */
id: string, 
/**
 * Short form (first 8 hex chars after the kind tag) for display.
 */
short_id: string, 
/**
 * Title.
 */
title: string, };
