// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One capability override on a register input.
 */
export type CapabilityOverrideInput = { 
/**
 * Capability key.
 */
key: string, 
/**
 * Override value.
 */
value: boolean, };
