// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the capability matrix.
 */
export type CapabilityRow = { 
/**
 * Capability key.
 */
capability: string, 
/**
 * Whether the identity holds it after defaults + overrides.
 */
granted: boolean, 
/**
 * Whether the value came from an explicit override (`true`) or the
 * kind default (`false`).
 */
overridden: boolean, };
