// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `key=value` capability override on an identity record.
 */
export type CapabilityOverride = { 
/**
 * Capability key (e.g. `can_promote_verified`).
 */
key: string, 
/**
 * Override value.
 */
value: boolean, };
