// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryKind } from "./MemoryKind";
import type { RiskClassInput } from "./RiskClassInput";

/**
 * Input for [`capture`].
 *
 * The CLI's `firetrail capture` reads the body from `--body` or stdin; ops
 * require it as an explicit field. Adapters fill it in before calling.
 */
export type CaptureInput = { 
/**
 * Memory kind. Defaults to [`MemoryKind::Memory`] when omitted.
 */
kind: MemoryKind, 
/**
 * Title / summary (required).
 */
title: string, 
/**
 * Body text (required; must be non-empty after trimming).
 */
body: string, 
/**
 * Tags (memory-kind only; ignored for other kinds).
 */
tags: Array<string>, 
/**
 * Risk classification.
 */
riskClass: RiskClassInput | null, 
/**
 * Owning scope.
 */
scope: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
