// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`claim`].
 */
export type ClaimInput = { 
/**
 * Ticket id (full canonical or unambiguous prefix).
 */
id: string, 
/**
 * Human-readable duration override (e.g. `"7d"`, `"12h"`). Defaults to
 * 7 days when omitted.
 */
expires: string | null, 
/**
 * Optional client-supplied correlation id; propagated onto the
 * emitted [`crate::Event::TicketClaimed`] envelope.
 */
request_id: string | null, };
