// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`close`].
 */
export type CloseInput = { 
/**
 * Ticket id (full canonical or unambiguous prefix).
 */
id: string, 
/**
 * Skip acceptance-criteria validation. Requires `reason`.
 */
force: boolean, 
/**
 * Reason for forcing the close. Required when `force` is `true`; recorded
 * as a `force_close_reason` label on the envelope.
 */
reason: string | null, 
/**
 * Optional client-supplied correlation id; propagated onto every
 * emitted [`crate::Event`] envelope.
 */
request_id: string | null, };
