// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single CODEOWNERS line.
 */
export type CodeOwnersRow = { 
/**
 * Raw glob pattern.
 */
pattern: string, 
/**
 * Owners (identity strings as they appear in the CODEOWNERS file).
 */
owners: Array<string>, };
