// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A component reference as the Profile panel renders it.
 *
 * The wire mirror of [`ft_core::ComponentRef`], kept in `ft-ops` so ts-rs only
 * ever sees ops types.
 */
export type ComponentView = { 
/**
 * Human-readable component name (e.g. `ft-cli`).
 */
name: string, 
/**
 * Repo-relative path to the component.
 */
path: string, 
/**
 * Optional one-line summary.
 */
summary: string | null, };
