// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketPriority } from "./TicketPriority";

/**
 * Input for [`create_epic`].
 */
export type CreateEpicInput = { 
/**
 * Title (required, non-empty).
 */
title: string, 
/**
 * Free-form description (markdown).
 */
description: string | null, 
/**
 * Priority.
 */
priority: TicketPriority | null, 
/**
 * Owning scope.
 */
scope: string | null, 
/**
 * `key=value` labels. Each entry must contain exactly one `=`.
 */
labels: Array<string>, 
/**
 * Optional client-supplied correlation id; propagated onto every
 * emitted [`crate::Event`] envelope so transports (the GUI in
 * particular) can coalesce optimistic updates with the server-sent
 * echo. CLI callers leave this `None`.
 */
request_id: string | null, };
