// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketPriority } from "./TicketPriority";

/**
 * Input for [`create_subtask`].
 */
export type CreateSubtaskInput = { 
/**
 * Title (required, non-empty).
 */
title: string, 
/**
 * Parent task id (required). Must resolve to a `Task`.
 */
parent: string, 
/**
 * Free-form description (markdown).
 */
description: string | null, 
/**
 * Priority.
 */
priority: TicketPriority | null, 
/**
 * Owner identity.
 */
owner: string | null, 
/**
 * Owning scope.
 */
scope: string | null, 
/**
 * `key=value` labels.
 */
labels: Array<string>, 
/**
 * Optional client-supplied correlation id (see [`CreateEpicInput::request_id`]).
 */
request_id: string | null, };
