// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiskClassInput } from "./RiskClassInput";

/**
 * Input for [`create_decision`].
 */
export type CreateDecisionInput = { 
/**
 * Short title.
 */
title: string, 
/**
 * Background / problem statement.
 */
context: string, 
/**
 * The decision itself.
 */
decision: string, 
/**
 * Consequences.
 */
consequences: string | null, 
/**
 * Risk classification.
 */
riskClass: RiskClassInput | null, 
/**
 * Owning scope.
 */
scope: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
