// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiskClassInput } from "./RiskClassInput";

/**
 * Input for [`create_runbook`].
 */
export type CreateRunbookInput = { 
/**
 * Short title.
 */
title: string, 
/**
 * One-line summary describing when to use the runbook.
 */
summary: string, 
/**
 * `applies_to` service names.
 */
appliesTo: Array<string>, 
/**
 * Risk classification.
 */
riskClass: RiskClassInput | null, 
/**
 * Owning scope.
 */
scope: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
