// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiskClassInput } from "./RiskClassInput";

/**
 * Input for [`create_memory`].
 */
export type CreateMemoryInput = { 
/**
 * Short title.
 */
title: string, 
/**
 * Markdown body.
 */
body: string, 
/**
 * Tags.
 */
tags: Array<string>, 
/**
 * Risk classification.
 */
riskClass: RiskClassInput | null, 
/**
 * Owning scope.
 */
scope: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
