// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiskClassInput } from "./RiskClassInput";
import type { SeverityInput } from "./SeverityInput";

/**
 * Input for [`create_incident`].
 */
export type CreateIncidentInput = { 
/**
 * One-line summary.
 */
summary: string, 
/**
 * Severity. Defaults to `sev3` when omitted.
 */
severity: SeverityInput | null, 
/**
 * RFC3339 instant the incident began. Defaults to "now".
 */
startedAt: string | null, 
/**
 * Comma-separated services affected (each entry trimmed).
 */
services: Array<string>, 
/**
 * Risk classification.
 */
riskClass: RiskClassInput | null, 
/**
 * Owning scope.
 */
scope: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
