// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiskClassInput } from "./RiskClassInput";

/**
 * Input for [`create_gotcha`].
 */
export type CreateGotchaInput = { 
/**
 * One-line summary.
 */
summary: string, 
/**
 * Markdown details.
 */
details: string | null, 
/**
 * Risk classification.
 */
riskClass: RiskClassInput | null, 
/**
 * Affected paths.
 */
affected: Array<string>, 
/**
 * Owning scope.
 */
scope: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
