// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketPriority } from "./TicketPriority";

/**
 * Input for [`create_bug`].
 */
export type CreateBugInput = { 
/**
 * Title (required, non-empty).
 */
title: string, 
/**
 * Free-form description (markdown).
 */
description: string | null, 
/**
 * Affected service.
 */
service: string | null, 
/**
 * Free-form severity tag (e.g. `"sev2"`).
 */
severity: string | null, 
/**
 * Priority.
 */
priority: TicketPriority | null, 
/**
 * Owning scope.
 */
scope: string | null, 
/**
 * `key=value` labels.
 */
labels: Array<string>, };
