// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`criteria_add`].
 */
export type CriteriaAddInput = { 
/**
 * Record id (Task / Subtask / Bug).
 */
id: string, 
/**
 * Criterion text (non-empty after trim).
 */
text: string, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
