// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriteriaListRow } from "./CriteriaListRow";

/**
 * Output of [`criteria_list`].
 */
export type CriteriaListOutput = { 
/**
 * Canonical record id.
 */
recordId: string, 
/**
 * AC rows.
 */
items: Array<CriteriaListRow>, };
