// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One AC row in [`CriteriaListOutput`].
 */
export type CriteriaListRow = { 
/**
 * 1-based position in the list.
 */
index: number, 
/**
 * Local id (e.g. `ac-01`).
 */
id: string, 
/**
 * Criterion text.
 */
text: string, 
/**
 * Whether the AC is checked.
 */
checked: boolean, 
/**
 * Attached evidence URL.
 */
evidenceUrl: string | null, };
