// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`criteria_check`] / [`criteria_uncheck`].
 */
export type CriteriaToggleInput = { 
/**
 * Record id.
 */
id: string, 
/**
 * AC id (`ac-01`) or 1-based index.
 */
which: string, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
