// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`criteria_list`].
 */
export type CriteriaListInput = { 
/**
 * Record id.
 */
id: string, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
