// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`criteria_evidence`].
 */
export type CriteriaEvidenceInput = { 
/**
 * Record id.
 */
id: string, 
/**
 * AC id or 1-based index.
 */
which: string, 
/**
 * Evidence URL (non-empty after trim).
 */
url: string, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
