// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle-status selector for [`create_decision`].
 *
 * Mirrors [`ft_core::DecisionStatus`]; kept separate so the wire surface
 * stays decoupled from the core enum (same pattern as [`SeverityInput`] /
 * [`RiskClassInput`]).
 */
export type DecisionStatusInput = "proposed" | "accepted" | "superseded" | "deprecated";
