// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State-change classification in the diff report.
 */
export type DiffChange = "created" | "modified" | "removed" | "renamed";
