// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`diff`].
 */
export type DiffInput = { 
/**
 * Base git ref.
 */
base: string, 
/**
 * Head git ref.
 */
head: string, 
/**
 * Restrict to memory-kind changes.
 */
memoryOnly: boolean, 
/**
 * Scope prefix filter.
 */
scope: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
