// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffChange } from "./DiffChange";

/**
 * One row of the diff report.
 */
export type DiffRow = { 
/**
 * Repo-relative path.
 */
path: string, 
/**
 * Resolved record id, if classifiable.
 */
id: string | null, 
/**
 * Record kind (lowercase).
 */
kind: string | null, 
/**
 * Coarse classification (`memory` / `structural` / `config` / `other`).
 */
class: string, 
/**
 * State change.
 */
change: DiffChange, 
/**
 * Owning scope, when present.
 */
scope: string | null, 
/**
 * One-line title at head (or base, on deletion), when available.
 */
title: string | null, };
