// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffRow } from "./DiffRow";

/**
 * Output of [`diff`].
 */
export type DiffOutput = { 
/**
 * Base ref echoed back.
 */
base: string, 
/**
 * Head ref echoed back.
 */
head: string, 
/**
 * Whether the `memory_only` filter was on.
 */
memoryOnlyFilter: boolean, 
/**
 * Scope filter prefix, if set.
 */
scopeFilter: string | null, 
/**
 * Per-record rows.
 */
rows: Array<DiffRow>, };
