// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Freshness of a linked doc's file relative to its indexed `content_hash`.
 *
 * The wire mirror of [`ft_embed::DocFreshness`] — kept in `ft-ops` so the
 * embed crate stays serialization-free and ts-rs only ever sees ops types.
 */
export type DocFreshnessView = "fresh" | "stale" | "missing";
