// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocFreshnessView } from "./DocFreshnessView";

/**
 * A linked doc as the ticket drawer renders it: pointer metadata + the raw
 * markdown content read live from the file + a freshness badge.
 */
export type DocView = { 
/**
 * Canonical doc record id.
 */
id: string, 
/**
 * Title (derived from the doc's H1, mirrored on the record).
 */
title: string, 
/**
 * Open taxonomy tag (`design` / `adr` / `runbook` / …).
 */
doc_type: string, 
/**
 * Repo-relative path to the backing `.md` file.
 */
path: string, 
/**
 * Short excerpt stored on the record (first prose paragraph).
 */
summary: string, 
/**
 * Freshness of the file relative to the indexed `content_hash`.
 */
freshness: DocFreshnessView, 
/**
 * Raw markdown read live from the file. Empty when [`DocFreshnessView::Missing`].
 */
content: string, };
