// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";

/**
 * Envelope wrapping every event with a correlation id.
 *
 * `request_id` is `None` for events emitted by background tasks; ops invoked
 * through a transport adapter should set it to the inbound request id so the
 * UI can coalesce optimistic state.
 */
export type EmittedEvent = { 
/**
 * Correlation id matching the originating request, if any.
 */
request_id: string | null, 
/**
 * The event payload.
 */
event: Event, };
