// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A summary row for one epic in [`EpicsOutput`].
 */
export type EpicSummary = { 
/**
 * Full canonical id.
 */
id: string, 
/**
 * Short form (first 8 hex chars after the kind tag) for display.
 */
short_id: string, 
/**
 * Title.
 */
title: string, 
/**
 * Status (lowercase, e.g. `"open"`, `"closed"`, `"in_progress"`).
 */
status: string, 
/**
 * Priority (lowercase, e.g. `"p1"`).
 */
priority: string, 
/**
 * Total direct-child tickets (tasks, subtasks, bugs) under this epic.
 */
child_total: number, 
/**
 * Children whose status is `Closed`.
 */
child_closed: number, 
/**
 * Acceptance criteria on the epic record itself.
 */
criteria_total: number, 
/**
 * Acceptance criteria on the epic that are checked.
 */
criteria_met: number, 
/**
 * `true` when all children are closed AND all own criteria are met AND the
 * epic is not already closed.
 */
ready_to_close: boolean, };
