// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardCard } from "./BoardCard";
import type { EpicSummary } from "./EpicSummary";

/**
 * Output of [`epics`].
 */
export type EpicsOutput = { 
/**
 * One summary per epic, sorted by title.
 */
epics: Array<EpicSummary>, 
/**
 * Maps epic canonical id → the [`BoardCard`]s for its children.
 */
children: { [key: string]: Array<BoardCard> }, };
