// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State-change notifications produced by ops.
 *
 * Starts intentionally small — Waves 1+ add more variants as the
 * corresponding ops land.
 */
export type Event = { "kind": "ticket_created", 
/**
 * Ticket id.
 */
id: string, } | { "kind": "ticket_transitioned", 
/**
 * Ticket id.
 */
id: string, 
/**
 * Previous state.
 */
from: string, 
/**
 * New state.
 */
to: string, } | { "kind": "memory_written", 
/**
 * Memory id.
 */
id: string, };
