// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SalvageDecision } from "./SalvageDecision";

/**
 * State-change notifications produced by ops.
 *
 * Starts intentionally small — Waves 1+ add more variants as the
 * corresponding ops land.
 */
export type Event = { "kind": "ticket_created", 
/**
 * Ticket id.
 */
id: string, } | { "kind": "ticket_updated", 
/**
 * Ticket id.
 */
id: string, } | { "kind": "ticket_transitioned", 
/**
 * Ticket id.
 */
id: string, 
/**
 * Previous state.
 */
from: string, 
/**
 * New state.
 */
to: string, } | { "kind": "ticket_claimed", 
/**
 * Ticket id.
 */
id: string, 
/**
 * Identity that holds the claim.
 */
actor: string, } | { "kind": "ticket_unclaimed", 
/**
 * Ticket id.
 */
id: string, } | { "kind": "ticket_closed", 
/**
 * Ticket id.
 */
id: string, } | { "kind": "ticket_linked", 
/**
 * Source ticket id.
 */
from: string, 
/**
 * Target ticket id.
 */
to: string, 
/**
 * Relation kind (serialized form, e.g. `"blocked-by"`).
 */
relation: string, } | { "kind": "doc_edited", 
/**
 * Doc record id.
 */
id: string, } | { "kind": "memory_written", 
/**
 * Memory id.
 */
id: string, } | { "kind": "memory_created", 
/**
 * Memory id.
 */
id: string, 
/**
 * Record kind (lowercase, e.g. `"incident"`, `"finding"`, …). Named
 * `record_kind` rather than `kind` because the parent enum uses
 * `kind` as its serde discriminator.
 */
record_kind: string, } | { "kind": "memory_salvaged", 
/**
 * Memory id.
 */
id: string, 
/**
 * Operator decision for this record.
 */
decision: SalvageDecision, } | { "kind": "scope_updated", 
/**
 * Canonical scope id.
 */
scope: string, } | { "kind": "identity_updated", 
/**
 * Canonical identity id.
 */
identity: string, 
/**
 * Field tags that changed (e.g. `["create"]`, `["status"]`).
 */
fields: Array<string>, } | { "kind": "trust_transitioned", 
/**
 * Memory id.
 */
id: string, 
/**
 * Previous trust state (lowercase, e.g. `"draft"`).
 */
from: string, 
/**
 * New trust state.
 */
to: string, } | { "kind": "review_approved", 
/**
 * Record id.
 */
id: string, } | { "kind": "review_rejected", 
/**
 * Record id.
 */
id: string, 
/**
 * Reason text.
 */
reason: string, } | { "kind": "lint_run", 
/**
 * Total findings produced.
 */
findings: number, } | { "kind": "verify_run", 
/**
 * `true` if every record passed chain verification.
 */
ok: boolean, };
