// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Evidence kind on a trust transition input.
 */
export type EvidenceKindInput = "incident_report" | "pull_request" | "commit" | "dashboard" | "log_query" | "test_result" | "jira_ticket" | "confluence_page" | "manual_note";
