// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The autocomplete result: a flat list of repo-relative, forward-slash paths.
 *
 * The wire mirror surfaced by `GET /api/files`, kept in `ft-ops` so ts-rs only
 * ever sees ops types (the xtask ts exporter depends on `ft-ops`, not `ft-ui`).
 */
export type FileListView = { 
/**
 * Suggested paths (or directory prefixes), sorted and deduped.
 */
paths: Array<string>, };
