// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ranked cross-domain hit. Unlike [`crate::memory::SearchHitOut`] this
 * carries the owning `scope` so the global palette can show + route by it.
 */
export type GlobalSearchHit = { 
/**
 * Document id (record id, or `<tag>:<key>` for synthetic docs).
 */
id: string, 
/**
 * Document kind (lowercase label, e.g. `task` / `memory` / `scope`).
 */
kind: string, 
/**
 * Title.
 */
title: string, 
/**
 * Ranking score (higher is better).
 */
score: number, 
/**
 * Trust state (lowercase).
 */
trust: string, 
/**
 * Owning scope, if any.
 */
scope: string | null, 
/**
 * Which signal produced this hit (`"lexical" | "vector" | "hybrid"`).
 */
mode: string, 
/**
 * Quarantine marker (only `true` for imported-but-unpromoted records).
 */
quarantine: boolean, };
