// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Walk direction selector.
 */
export type GraphDirectionInput = "up" | "down" | "both";
