// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node in the result graph.
 */
export type GraphNode = { 
/**
 * Canonical record id.
 */
id: string, 
/**
 * Record kind (lowercase, e.g. `"task"`).
 */
kind: string, 
/**
 * Title at the time of the walk (empty when unknown).
 */
title: string, };
