// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphEdge } from "./GraphEdge";
import type { GraphNode } from "./GraphNode";

/**
 * Output of [`graph`].
 */
export type GraphOutput = { 
/**
 * Root id (canonical).
 */
root: string, 
/**
 * Walk depth requested.
 */
depth: number, 
/**
 * Walk direction (echoed back as lowercase string).
 */
direction: string, 
/**
 * Distinct nodes (root included).
 */
nodes: Array<GraphNode>, 
/**
 * All edges discovered during the walk.
 */
edges: Array<GraphEdge>, 
/**
 * `true` when the node count hit [`MAX_GRAPH_NODES`] and the result was
 * truncated. Edges pointing at dropped nodes are omitted, so the returned
 * `nodes`/`edges` remain internally consistent.
 */
truncated: boolean, 
/**
 * Self-describing reason when the walk found no edges.
 */
reason: string | null, };
