// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One edge in the result graph.
 */
export type GraphEdge = { 
/**
 * Source id.
 */
from: string, 
/**
 * Target id.
 */
to: string, 
/**
 * Relation kind (e.g. `"parent_epic"`, `"depends_on"`).
 */
kind: string, 
/**
 * 0-based depth from the root.
 */
depth: number, };
