// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphDirectionInput } from "./GraphDirectionInput";

/**
 * Input for [`graph`].
 */
export type GraphInput = { 
/**
 * Root id (full canonical or unambiguous prefix).
 */
id: string, 
/**
 * Walk direction.
 */
direction: GraphDirectionInput, 
/**
 * Walk depth (minimum 1).
 */
depth: number, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
