// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityOverride } from "./CapabilityOverride";

/**
 * Wire-friendly view of a single registered identity.
 */
export type IdentityView = { 
/**
 * Canonical id.
 */
id: string, 
/**
 * Display name.
 */
name: string, 
/**
 * Identity kind (`human` / `bot` / `ci`).
 */
kind: string, 
/**
 * Lifecycle status (`active` / `offboarded`).
 */
status: string, 
/**
 * Email aliases.
 */
emails: Array<string>, 
/**
 * Machine hostnames.
 */
machines: Array<string>, 
/**
 * Capability overrides as a flat key/value list (only keys explicitly
 * set in the registry; defaults are not flattened here — see
 * [`super::capabilities`] for the effective matrix).
 */
capabilities: Array<CapabilityOverride>, };
