// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityStatusFilter } from "./IdentityStatusFilter";

/**
 * Input for [`list`].
 */
export type IdentityListInput = { 
/**
 * Filter by lifecycle status.
 */
status: IdentityStatusFilter | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
