// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityView } from "./IdentityView";

/**
 * Output of [`list`].
 */
export type IdentityListOutput = { 
/**
 * Identities, in registry order.
 */
identities: Array<IdentityView>, };
