// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status filter for [`list`]. Mirrors `ft_identity::IdentityStatus`.
 */
export type IdentityStatusFilter = "active" | "offboarded";
