// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`capabilities`].
 */
export type IdentityCapabilitiesInput = { 
/**
 * Identity id to look up.
 */
id: string, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
