// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`offboard`].
 */
export type IdentityOffboardInput = { 
/**
 * Identity id to offboard.
 */
id: string, 
/**
 * Whether to walk every record and release the identity's claims.
 */
sweepClaims: boolean, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
