// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityRow } from "./CapabilityRow";

/**
 * Output of [`capabilities`].
 */
export type IdentityCapabilitiesOutput = { 
/**
 * Identity id.
 */
identity: string, 
/**
 * Identity kind (`human` / `bot` / `ci`).
 */
kind: string, 
/**
 * Lifecycle status.
 */
status: string, 
/**
 * Effective capability matrix (defaults + overrides composed).
 */
capabilities: Array<CapabilityRow>, };
