// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityView } from "./IdentityView";

/**
 * Output of [`register`].
 */
export type IdentityRegisterOutput = { 
/**
 * The identity that was written.
 */
identity: IdentityView, };
