// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityOverrideInput } from "./CapabilityOverrideInput";
import type { IdentityKindInput } from "./IdentityKindInput";

/**
 * Input for [`register`].
 */
export type IdentityRegisterInput = { 
/**
 * Canonical short id (e.g. `alice`, `bot-claude`).
 */
id: string, 
/**
 * Human-readable display name.
 */
name: string, 
/**
 * Email aliases (must be non-empty).
 */
emails: Array<string>, 
/**
 * Identity kind.
 */
kind: IdentityKindInput, 
/**
 * Machine hostnames.
 */
machines: Array<string>, 
/**
 * `key=value` capability overrides parsed by the caller. The CLI splits
 * `--capability key=value` flags; the GUI submits an already-parsed
 * list.
 */
capabilities: Array<CapabilityOverrideInput>, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
