// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identity-kind selector for [`register`].
 */
export type IdentityKindInput = "human" | "bot" | "ci";
