// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityView } from "./IdentityView";

/**
 * Output of [`show`].
 */
export type IdentityShowOutput = { 
/**
 * The resolved identity.
 */
identity: IdentityView, };
