// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketRelationKind } from "./TicketRelationKind";

/**
 * Input for [`link`].
 */
export type LinkInput = { 
/**
 * Source ticket id (full canonical or unambiguous prefix).
 */
from: string, 
/**
 * Target ticket id.
 */
to: string, 
/**
 * Relation kind.
 */
kind: TicketRelationKind, 
/**
 * Optional client-supplied correlation id; propagated onto the
 * emitted [`crate::Event::TicketLinked`] envelope.
 */
request_id: string | null, };
