// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LintFinding } from "./LintFinding";

/**
 * Output of [`lint`].
 */
export type LintOutput = { 
/**
 * Records scanned.
 */
scanned: number, 
/**
 * Number of error-severity findings.
 */
errors: number, 
/**
 * Number of warning-severity findings.
 */
warnings: number, 
/**
 * All findings.
 */
findings: Array<LintFinding>, };
