// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LintSeverity } from "./LintSeverity";

/**
 * One lint finding.
 */
export type LintFinding = { 
/**
 * Severity bucket.
 */
severity: LintSeverity, 
/**
 * Rule id (e.g. `"ac_cap_exceeded"`).
 */
rule: string, 
/**
 * Record id (or file path when the record failed to parse).
 */
recordId: string, 
/**
 * Human-readable message.
 */
message: string, 
/**
 * Suggested remediation. Populated when `fix_hints` was on.
 */
suggestedFix: string | null, };
