// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`lint`].
 */
export type LintInput = { 
/**
 * Emit suggested-fix hints on every finding.
 */
fixHints: boolean, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
