// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of [`ListOutput`].
 */
export type ListedTicket = { 
/**
 * Full canonical id.
 */
id: string, 
/**
 * Record kind (serialized name, e.g. `"task"`).
 */
kind: string, 
/**
 * Title.
 */
title: string, 
/**
 * Status (serialized form, e.g. `"in_progress"`).
 */
status: string, 
/**
 * Priority (lowercase, e.g. `"p1"`).
 */
priority: string, 
/**
 * Owner identity if set.
 */
owner: string | null, 
/**
 * Owning scope if set.
 */
scope: string | null, };
