// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketKindFilter } from "./TicketKindFilter";
import type { TicketStatusFilter } from "./TicketStatusFilter";

/**
 * Input for [`list`].
 */
export type ListInput = { 
/**
 * Restrict to a kind.
 */
kind: TicketKindFilter | null, 
/**
 * Restrict to a status (implies `include_closed` + `include_archived` so
 * the status filter is the only gate).
 */
status: TicketStatusFilter | null, 
/**
 * Restrict to a specific owner identity.
 */
owner: string | null, 
/**
 * Restrict to records under a scope id.
 */
scope: string | null, 
/**
 * Cap the number of results.
 */
limit: bigint | null, 
/**
 * Skip the first N results.
 */
offset: bigint | null, 
/**
 * When `true`, returns only unblocked records (records that have no
 * open blockers and no active claim). Mirrors the CLI's
 * `firetrail ready` command. When set, the `status` and `offset`
 * filters are ignored (the index's ready query has its own gating).
 */
ready: boolean, };
