// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryRowOut } from "./MemoryRowOut";

/**
 * Output of [`list`] / [`stale`].
 */
export type MemoryListOutput = { 
/**
 * Matching rows.
 */
rows: Array<MemoryRowOut>, };
