// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryKind } from "./MemoryKind";

/**
 * Input for [`stale`].
 */
export type MemoryStaleInput = { 
/**
 * Restrict to one memory kind.
 */
kind: MemoryKind | null, };
