// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the list / stale response.
 */
export type MemoryRowOut = { 
/**
 * Canonical record id.
 */
id: string, 
/**
 * Memory kind (lowercase string).
 */
kind: string, 
/**
 * Title / summary.
 */
title: string, 
/**
 * Trust state.
 */
trust: string | null, 
/**
 * Risk class.
 */
riskClass: string | null, 
/**
 * Freshness flag.
 */
stale: boolean, };
