// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`show`].
 */
export type MemoryShowInput = { 
/**
 * Memory id (full canonical form or unambiguous prefix).
 */
id: string, };
