// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryKind } from "./MemoryKind";
import type { RiskClassInput } from "./RiskClassInput";
import type { TrustStateInput } from "./TrustStateInput";

/**
 * Input for [`list`].
 */
export type MemoryListInput = { 
/**
 * Restrict to one memory kind. `None` means all six.
 */
kind: MemoryKind | null, 
/**
 * Filter by trust state.
 */
trust: TrustStateInput | null, 
/**
 * Filter by risk class.
 */
riskClass: RiskClassInput | null, 
/**
 * Only return records past their freshness window.
 */
stale: boolean, 
/**
 * Cap the number of rows.
 */
limit: bigint | null, };
