// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentView } from "./ComponentView";

/**
 * The repo profile as the Profile panel renders it: the record id, every
 * command/tooling field, the component map, notes, and the trust state (as a
 * serialized lowercase string, e.g. `"draft"`).
 */
export type ProfileView = { 
/**
 * Canonical profile record id.
 */
id: string, 
/**
 * The canonical "prove a change is good" command.
 */
validate_command: string | null, 
/**
 * Standard test command.
 */
test_command: string | null, 
/**
 * Standard build command.
 */
build_command: string | null, 
/**
 * Standard lint command.
 */
lint_command: string | null, 
/**
 * Primary language(s).
 */
languages: Array<string>, 
/**
 * Package manager(s).
 */
package_managers: Array<string>, 
/**
 * Optional runtime note.
 */
runtime: string | null, 
/**
 * Shallow component map (names + paths only).
 */
components: Array<ComponentView>, 
/**
 * Free-form notes.
 */
notes: string | null, 
/**
 * Trust state (lowercase, e.g. `"draft"`, `"reviewed"`, `"verified"`).
 */
trust: string, };
