// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One acceptance-criterion row.
 */
export type ReviewAcRow = { 
/**
 * Local id.
 */
id: string, 
/**
 * Criterion text.
 */
text: string, 
/**
 * `checked` / `unchecked`.
 */
status: string, 
/**
 * Whether the AC was marked proposed.
 */
proposed: boolean, 
/**
 * Attached evidence URL.
 */
evidenceUrl: string | null, };
