// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One history row.
 */
export type ReviewHistoryRow = { 
/**
 * 0-based index in the chain.
 */
index: number, 
/**
 * Number of ops compacted into this entry.
 */
opsCount: number, 
/**
 * PR number, if known.
 */
mergedViaPr: bigint | null, 
/**
 * RFC3339 timestamp.
 */
timestamp: string, 
/**
 * Acting identity.
 */
actor: string, 
/**
 * Compacted ops summary lines.
 */
opsSummary: Array<string>, 
/**
 * `to_hash` for this entry.
 */
toHash: string, };
