// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One evidence row.
 */
export type ReviewEvidenceRow = { 
/**
 * Local id.
 */
id: string, 
/**
 * Evidence kind.
 */
kind: string, 
/**
 * URL.
 */
url: string, 
/**
 * Free-form description.
 */
description: string | null, };
