// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Risk-class selector (ADR-0013).
 */
export type RiskClassInput = "security" | "availability" | "data-loss" | "compliance" | "performance" | "correctness";
