// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SalvageEntryAction } from "./SalvageEntryAction";

/**
 * One candidate record's outcome.
 */
export type SalvageEntry = { 
/**
 * Canonical record id (uppercased prefix).
 */
id: string, 
/**
 * Memory kind (`finding`, `task`, …).
 */
kind: string, 
/**
 * Selected action.
 */
action: SalvageEntryAction, 
/**
 * Human-readable reason for the action.
 */
reason: string, 
/**
 * Repo-relative path of the record blob on the source branch.
 */
path: string, };
