// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SalvageEntry } from "./SalvageEntry";

/**
 * Output of [`salvage`].
 */
export type SalvageOutput = { 
/**
 * Base branch the diff was computed against.
 */
base: string, 
/**
 * Source branch (when not detached).
 */
sourceBranch: string | null, 
/**
 * Resolved source ref (branch name or SHA when detached).
 */
sourceRef: string, 
/**
 * Per-record decisions.
 */
entries: Array<SalvageEntry>, 
/**
 * New salvage branch name. `None` when nothing was salvaged or
 * `dry_run = true`.
 */
salvageBranch: string | null, 
/**
 * Mirrors `input.dry_run`.
 */
dryRun: boolean, 
/**
 * Non-fatal warnings.
 */
warnings: Array<string>, };
