// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-record outcome of the salvage workflow.
 */
export type SalvageDecision = "accepted" | "rejected";
