// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`salvage`].
 */
export type SalvageInput = { 
/**
 * Base branch to compare against. Defaults to `"main"`.
 */
base: string, 
/**
 * Salvage source branch. `None` means the current branch (or HEAD
 * if detached).
 */
branch: string | null, 
/**
 * Plan-only: do not mutate the repo. Use this to enumerate candidates
 * before submitting an explicit selection.
 */
dryRun: boolean, 
/**
 * Explicit accept-list of record ids. `None` falls back to kind-based
 * defaults (memory salvages, structural skips). When `Some`, every
 * candidate whose id is not in the list is force-skipped.
 */
selected: Array<string> | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
