// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-record decision in [`SalvageOutput`].
 */
export type SalvageEntryAction = "salvaged" | "skipped";
