// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeDetail } from "./ScopeDetail";

/**
 * Output of [`show`].
 */
export type ScopeShowOutput = { 
/**
 * The scope's full detail.
 */
scope: ScopeDetail, };
