// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeYamlView } from "./ScopeYamlView";

/**
 * Output of every scope *write* op (`add` / `edit` / `remove` / `reorder`).
 *
 * Carries the full, post-write scopes list in declaration order so the editor
 * can re-render without a follow-up `GET /api/scope`.
 */
export type ScopeWriteOutput = { 
/**
 * The full scopes list after the write, in declaration order.
 */
scopes: Array<ScopeYamlView>, };
