// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`edit`] — partial update of an existing scope, by id.
 *
 * Every field is `Option`: `None` leaves the stored value untouched. The
 * nullable fields (`name`, `codeowners`) use `Option<Option<T>>` so the editor
 * can distinguish "leave alone" (`None`) from "clear" (`Some(None)`). Vec
 * fields replace the stored list when `Some` (an empty `Some(vec![])` clears
 * it — validation then rejects an empty `applies_to`).
 */
export type ScopeEditInput = { 
/**
 * New display name (`Some(None)` clears it).
 */
name: string | null | null, 
/**
 * Replacement `applies_to` glob list.
 */
appliesTo: Array<string> | null, 
/**
 * Replacement alias list.
 */
aliases: Array<string> | null, 
/**
 * New CODEOWNERS path (`Some(None)` clears it).
 */
codeowners: string | null | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
