// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`add`] — a complete new scope (becomes last-declared).
 */
export type ScopeInput = { 
/**
 * Canonical scope id (unique).
 */
id: string, 
/**
 * Optional display name.
 */
name: string | null, 
/**
 * `applies_to` glob patterns (at least one required).
 */
appliesTo: Array<string>, 
/**
 * Declared aliases.
 */
aliases: Array<string>, 
/**
 * Optional CODEOWNERS path (repo-relative).
 */
codeowners: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
