// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`show`].
 */
export type ScopeShowInput = { 
/**
 * Scope id or alias.
 */
id: string, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
