// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AliasEntry } from "./AliasEntry";

/**
 * Output of [`aliases`].
 */
export type ScopeAliasesOutput = { 
/**
 * Alphabetical alias → scope-id entries.
 */
aliases: Array<AliasEntry>, };
