// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`owners`].
 */
export type ScopeOwnersInput = { 
/**
 * Repo-relative or absolute path to look up.
 */
path: string, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
