// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-scope preview row: how many tracked files the scope matches.
 */
export type ScopeMatchRow = { 
/**
 * Canonical scope id.
 */
id: string, 
/**
 * Tracked files (at `HEAD`) this scope's globs match.
 */
matchCount: number, };
