// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary view of a single scope (used by [`list`] and [`show`]).
 */
export type ScopeSummary = { 
/**
 * Canonical id.
 */
id: string, 
/**
 * Display name.
 */
name: string, 
/**
 * `applies_to` glob patterns.
 */
appliesTo: Array<string>, 
/**
 * Declared aliases (excluding the implicit self-alias).
 */
aliases: Array<string>, 
/**
 * Whether a CODEOWNERS file is wired to this scope.
 */
hasCodeowners: boolean, };
