// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeOwnersRow } from "./CodeOwnersRow";
import type { ScopeSummary } from "./ScopeSummary";

/**
 * Detail view of a single scope.
 */
export type ScopeDetail = { 
/**
 * Summary fields.
 */
summary: ScopeSummary, 
/**
 * Parsed CODEOWNERS entries.
 */
codeowners: Array<CodeOwnersRow>, };
