// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One scope as the editor renders it after a write (declaration order).
 *
 * The raw [`ScopeYaml`] mirror (so the editor can round-trip a write without
 * re-deriving `name`/`aliases` from the compiled registry).
 */
export type ScopeYamlView = { 
/**
 * Canonical id.
 */
id: string, 
/**
 * Display name (if set).
 */
name: string | null, 
/**
 * `applies_to` glob patterns.
 */
appliesTo: Array<string>, 
/**
 * Declared aliases.
 */
aliases: Array<string>, 
/**
 * CODEOWNERS path (string form, if set).
 */
codeowners: string | null, };
