// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeMatchRow } from "./ScopeMatchRow";

/**
 * Output of [`preview`] — per-scope match counts plus advisory warnings.
 *
 * Warnings mirror the doctor's per-scope checks: a scope matching zero tracked
 * files, and a later-declared broad scope shadowing an earlier narrower one.
 */
export type ScopePreviewView = { 
/**
 * Per-scope match counts, in declaration order.
 */
scopes: Array<ScopeMatchRow>, 
/**
 * Advisory warnings (zero-match globs, broad-last shadowing).
 */
warnings: Array<string>, };
