// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of [`owners`].
 */
export type ScopeOwnersOutput = { 
/**
 * Resolved path (string form).
 */
path: string, 
/**
 * Identity strings, in CODEOWNERS order.
 */
owners: Array<string>, };
