// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeSummary } from "./ScopeSummary";

/**
 * Output of [`list`].
 */
export type ScopeListOutput = { 
/**
 * Every scope, in load order.
 */
scopes: Array<ScopeSummary>, };
