// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchHitOut } from "./SearchHitOut";

/**
 * Output of [`search`] / [`similar`].
 */
export type SearchOutput = { 
/**
 * Resolved mode label (after any degradation).
 */
mode: string, 
/**
 * Ranked hits, highest score first.
 */
hits: Array<SearchHitOut>, 
/**
 * Non-fatal warnings (e.g. "vector search unavailable; degraded to
 * lexical").
 */
warnings: Array<string>, };
