// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A search-layer kind the caller can filter on. Mirrors
 * [`ft_search::IndexKind`] as a flat, ts-rs-exportable enum (the record
 * variants are inlined so the wire shape is a single string union, matching
 * the lowercase labels the engine already uses).
 */
export type SearchKind = "epic" | "task" | "subtask" | "bug" | "incident" | "finding" | "runbook" | "decision" | "gotcha" | "memory" | "doc" | "scope" | "identity" | "audit";
