// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ranked hit.
 */
export type SearchHitOut = { 
/**
 * Record id.
 */
id: string, 
/**
 * Record kind (lowercase).
 */
kind: string, 
/**
 * Title.
 */
title: string, 
/**
 * Ranking score (higher is better).
 */
score: number, 
/**
 * Trust state (lowercase).
 */
trust: string, 
/**
 * Which signal produced this hit (`"lexical" | "vector" | "hybrid"`).
 */
mode: string, 
/**
 * Quarantine marker (only `true` for imported-but-unpromoted records).
 */
quarantine: boolean, };
