// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire shape for the requested search mode.
 */
export type SearchMode = "auto" | "lexical" | "vector" | "hybrid";
