// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryKind } from "./MemoryKind";
import type { SearchMode } from "./SearchMode";
import type { TrustStateInput } from "./TrustStateInput";

/**
 * Input for [`search`].
 */
export type SearchInput = { 
/**
 * Free-text query string.
 */
query: string, 
/**
 * Mode. Defaults to [`SearchMode::Auto`].
 */
mode: SearchMode, 
/**
 * Minimum trust floor.
 */
trust: TrustStateInput | null, 
/**
 * Restrict to memory kinds. Empty means "all kinds".
 */
kinds: Array<MemoryKind>, 
/**
 * Restrict to owning scope.
 */
scope: string | null, 
/**
 * Cap the number of hits. Defaults to 20.
 */
limit: number, 
/**
 * Include quarantined (imported but not yet promoted) records.
 */
includeQuarantine: boolean, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
