// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity selector for [`create_incident`] and [`capture`] (incident form).
 */
export type SeverityInput = "sev1" | "sev2" | "sev3" | "sev4";
