// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`similar`].
 */
export type SimilarInput = { 
/**
 * Source record id (full or unambiguous prefix).
 */
id: string, 
/**
 * Cap the number of hits. Defaults to 10.
 */
limit: number, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
