// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind filter for [`ListInput::kind`].
 *
 * Mirrors the structural kinds (`epic`/`task`/`subtask`/`bug`); memory kinds
 * belong to the `memory` ops module landing in Wave 2.
 */
export type TicketKindFilter = "epic" | "task" | "subtask" | "bug";
