// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire form of [`ft_core::RelationKind`].
 *
 * Mirrors the kebab-case serde representation of the core enum.
 */
export type TicketRelationKind = "blocks" | "blocked-by" | "parent-of" | "child-of" | "related-to" | "duplicates" | "supersedes" | "fixed-by" | "caused-by";
