// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status filter for [`ListInput::status`].
 */
export type TicketStatusFilter = "open" | "ready" | "in_progress" | "review" | "blocked" | "closed" | "deferred" | "archived";
