// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Priority selector used in create / update inputs.
 */
export type TicketPriority = "p0" | "p1" | "p2" | "p3" | "p4";
