// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceKindInput } from "./EvidenceKindInput";

/**
 * Input for [`promote`].
 */
export type TrustPromoteInput = { 
/**
 * Memory id.
 */
id: string, 
/**
 * Optional reason text.
 */
reason: string | null, 
/**
 * Evidence URL (required for high-stakes risk classes per ADR-0013).
 */
evidenceUrl: string | null, 
/**
 * Evidence kind.
 */
evidenceType: EvidenceKindInput | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
