// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trust-state filter on the wire. Mirrors `ft_core::TrustState`.
 */
export type TrustStateInput = "draft" | "reviewed" | "verified" | "stale" | "deprecated" | "archived" | "superseded" | "rejected" | "redacted";
