// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`deprecate`] / [`redact`].
 */
export type TrustReasonInput = { 
/**
 * Memory id.
 */
id: string, 
/**
 * Reason text (required).
 */
reason: string, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
