// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`merge`].
 */
export type TrustMergeInput = { 
/**
 * Canonical id (every `others` entry is superseded by this id).
 */
canonical: string, 
/**
 * Ids to merge into `canonical`.
 */
others: Array<string>, 
/**
 * Optional reason text.
 */
reason: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
