// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`review`].
 */
export type TrustReviewInput = { 
/**
 * Memory id (full canonical or unambiguous prefix).
 */
id: string, 
/**
 * Optional reason text.
 */
reason: string | null, 
/**
 * Optional evidence URL.
 */
evidenceUrl: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
