// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`supersede`].
 */
export type TrustSupersedeInput = { 
/**
 * Memory id being superseded.
 */
id: string, 
/**
 * Successor memory id.
 */
successor: string, 
/**
 * Optional reason text.
 */
reason: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
