// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`unclaim`].
 */
export type UnclaimInput = { 
/**
 * Ticket id.
 */
id: string, 
/**
 * Release another actor's claim. When `true`, the caller must either be
 * the existing claimant, the existing claim must be expired, or the
 * caller must hold the admin capability.
 */
takeover: boolean, 
/**
 * Required when `takeover` is `true`.
 */
reason: string | null, 
/**
 * Optional client-supplied correlation id; propagated onto the
 * emitted [`crate::Event::TicketUnclaimed`] envelope.
 */
request_id: string | null, };
