// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketPriority } from "./TicketPriority";
import type { TicketStatusFilter } from "./TicketStatusFilter";

/**
 * Input for [`update`].
 *
 * Every field is optional; the op fails with [`OpsError::Validation`] if no
 * fields are supplied (matching the CLI's "at least one of …" behaviour).
 */
export type UpdateInput = { 
/**
 * Ticket id (full canonical or unambiguous prefix).
 */
id: string, 
/**
 * New title. Trimmed; rejected if empty.
 */
title: string | null, 
/**
 * New status.
 */
status: TicketStatusFilter | null, 
/**
 * New priority.
 */
priority: TicketPriority | null, 
/**
 * New owner identity. Pass an empty / whitespace-only string to clear.
 */
owner: string | null, 
/**
 * New description. Only valid on epic / task / subtask / bug.
 */
description: string | null, };
