// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`update`] — partial update of the profile.
 *
 * The `Option<Option<T>>` fields are deliberate: the outer layer distinguishes
 * "field untouched" (`None`) from "set / clear it" (`Some(..)`), which a flat
 * `Option<T>` cannot express for a partial update of nullable fields. Vec
 * fields overwrite the corresponding slice when present; `None` leaves it
 * untouched.
 */
export type UpdateProfileInput = { 
/**
 * New validate command (`Some(None)` clears it).
 */
validateCommand: string | null | null, 
/**
 * New test command.
 */
testCommand: string | null | null, 
/**
 * New build command.
 */
buildCommand: string | null | null, 
/**
 * New lint command.
 */
lintCommand: string | null | null, 
/**
 * Replacement language list.
 */
languages: Array<string> | null, 
/**
 * Replacement package-manager list.
 */
packageManagers: Array<string> | null, 
/**
 * New runtime note.
 */
runtime: string | null | null, 
/**
 * New free-form notes.
 */
notes: string | null | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
