// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidateEntryView } from "./ValidateEntryView";

/**
 * The set of distinct validate commands a changeset requires — the wire mirror
 * of [`resolve::ValidatePlan`], surfaced by `GET /api/profile/resolve` and
 * `firetrail profile resolve`.
 */
export type ValidatePlanView = { 
/**
 * Distinct commands, ordered by command string.
 */
entries: Array<ValidateEntryView>, 
/**
 * Changed files whose resolved profile has no validate command.
 */
unresolved: number, };
