// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One distinct validate command in a [`ValidatePlanView`], with provenance —
 * the wire mirror of [`resolve::ValidateEntry`].
 */
export type ValidateEntryView = { 
/**
 * The validate command to run.
 */
command: string, 
/**
 * Scope ids (sorted, unique) that resolved to this command. Empty = base.
 */
scopes: Array<string>, 
/**
 * How many changed files resolved to this command.
 */
fileCount: number, };
