// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerifyResult } from "./VerifyResult";

/**
 * Output of [`verify`].
 */
export type VerifyOutput = { 
/**
 * Total records inspected.
 */
total: number, 
/**
 * Records that failed verification.
 */
failures: number, 
/**
 * Per-record verdicts.
 */
results: Array<VerifyResult>, };
