// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-record verdict.
 */
export type VerifyResult = { 
/**
 * Canonical record id (or file path when the record failed to parse).
 */
id: string, 
/**
 * `true` if the chain verified.
 */
ok: boolean, 
/**
 * First failure reason (`None` when `ok`).
 */
reason: string | null, };
