// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for [`verify`].
 *
 * When `id` is `Some`, verify only that record; when `None`, walk every
 * record file directly so corrupted records surface as per-record failures
 * rather than aborting the whole pass.
 */
export type VerifyInput = { 
/**
 * Specific record id (full canonical) or `None` for "every record".
 */
id: string | null, 
/**
 * Optional client-supplied correlation id.
 */
requestId: string | null, };
