/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScopeIndexRouteImport } from './routes/scope/index'
import { Route as MemoryIndexRouteImport } from './routes/memory/index'
import { Route as IdentityIndexRouteImport } from './routes/identity/index'
import { Route as EpicsIndexRouteImport } from './routes/epics/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as TicketsIdRouteImport } from './routes/tickets/$id'
import { Route as ScopeIdRouteImport } from './routes/scope/$id'
import { Route as MemorySearchRouteImport } from './routes/memory/search'
import { Route as MemorySalvageRouteImport } from './routes/memory/salvage'
import { Route as MemoryIdRouteImport } from './routes/memory/$id'
import { Route as IdentityIdRouteImport } from './routes/identity/$id'
import { Route as AuditVerifyRouteImport } from './routes/audit/verify'
import { Route as AuditLintRouteImport } from './routes/audit/lint'
import { Route as AuditGraphRouteImport } from './routes/audit/graph'
import { Route as AuditDiffRouteImport } from './routes/audit/diff'
import { Route as AuditReviewRecordIdRouteImport } from './routes/audit/review.$recordId'
import { Route as AuditCriteriaRecordIdRouteImport } from './routes/audit/criteria.$recordId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeIndexRoute = ScopeIndexRouteImport.update({
  id: '/scope/',
  path: '/scope/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityIndexRoute = IdentityIndexRouteImport.update({
  id: '/identity/',
  path: '/identity/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpicsIndexRoute = EpicsIndexRouteImport.update({
  id: '/epics/',
  path: '/epics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeIdRoute = ScopeIdRouteImport.update({
  id: '/scope/$id',
  path: '/scope/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorySearchRoute = MemorySearchRouteImport.update({
  id: '/memory/search',
  path: '/memory/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorySalvageRoute = MemorySalvageRouteImport.update({
  id: '/memory/salvage',
  path: '/memory/salvage',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIdRoute = MemoryIdRouteImport.update({
  id: '/memory/$id',
  path: '/memory/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityIdRoute = IdentityIdRouteImport.update({
  id: '/identity/$id',
  path: '/identity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditVerifyRoute = AuditVerifyRouteImport.update({
  id: '/audit/verify',
  path: '/audit/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLintRoute = AuditLintRouteImport.update({
  id: '/audit/lint',
  path: '/audit/lint',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditGraphRoute = AuditGraphRouteImport.update({
  id: '/audit/graph',
  path: '/audit/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditDiffRoute = AuditDiffRouteImport.update({
  id: '/audit/diff',
  path: '/audit/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditReviewRecordIdRoute = AuditReviewRecordIdRouteImport.update({
  id: '/audit/review/$recordId',
  path: '/audit/review/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditCriteriaRecordIdRoute = AuditCriteriaRecordIdRouteImport.update({
  id: '/audit/criteria/$recordId',
  path: '/audit/criteria/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/profile': typeof ProfileRoute
  '/audit/diff': typeof AuditDiffRoute
  '/audit/graph': typeof AuditGraphRoute
  '/audit/lint': typeof AuditLintRoute
  '/audit/verify': typeof AuditVerifyRoute
  '/identity/$id': typeof IdentityIdRoute
  '/memory/$id': typeof MemoryIdRoute
  '/memory/salvage': typeof MemorySalvageRoute
  '/memory/search': typeof MemorySearchRoute
  '/scope/$id': typeof ScopeIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/audit/': typeof AuditIndexRoute
  '/epics/': typeof EpicsIndexRoute
  '/identity/': typeof IdentityIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/scope/': typeof ScopeIndexRoute
  '/audit/criteria/$recordId': typeof AuditCriteriaRecordIdRoute
  '/audit/review/$recordId': typeof AuditReviewRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/profile': typeof ProfileRoute
  '/audit/diff': typeof AuditDiffRoute
  '/audit/graph': typeof AuditGraphRoute
  '/audit/lint': typeof AuditLintRoute
  '/audit/verify': typeof AuditVerifyRoute
  '/identity/$id': typeof IdentityIdRoute
  '/memory/$id': typeof MemoryIdRoute
  '/memory/salvage': typeof MemorySalvageRoute
  '/memory/search': typeof MemorySearchRoute
  '/scope/$id': typeof ScopeIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/audit': typeof AuditIndexRoute
  '/epics': typeof EpicsIndexRoute
  '/identity': typeof IdentityIndexRoute
  '/memory': typeof MemoryIndexRoute
  '/scope': typeof ScopeIndexRoute
  '/audit/criteria/$recordId': typeof AuditCriteriaRecordIdRoute
  '/audit/review/$recordId': typeof AuditReviewRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/profile': typeof ProfileRoute
  '/audit/diff': typeof AuditDiffRoute
  '/audit/graph': typeof AuditGraphRoute
  '/audit/lint': typeof AuditLintRoute
  '/audit/verify': typeof AuditVerifyRoute
  '/identity/$id': typeof IdentityIdRoute
  '/memory/$id': typeof MemoryIdRoute
  '/memory/salvage': typeof MemorySalvageRoute
  '/memory/search': typeof MemorySearchRoute
  '/scope/$id': typeof ScopeIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/audit/': typeof AuditIndexRoute
  '/epics/': typeof EpicsIndexRoute
  '/identity/': typeof IdentityIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/scope/': typeof ScopeIndexRoute
  '/audit/criteria/$recordId': typeof AuditCriteriaRecordIdRoute
  '/audit/review/$recordId': typeof AuditReviewRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backlog'
    | '/profile'
    | '/audit/diff'
    | '/audit/graph'
    | '/audit/lint'
    | '/audit/verify'
    | '/identity/$id'
    | '/memory/$id'
    | '/memory/salvage'
    | '/memory/search'
    | '/scope/$id'
    | '/tickets/$id'
    | '/audit/'
    | '/epics/'
    | '/identity/'
    | '/memory/'
    | '/scope/'
    | '/audit/criteria/$recordId'
    | '/audit/review/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backlog'
    | '/profile'
    | '/audit/diff'
    | '/audit/graph'
    | '/audit/lint'
    | '/audit/verify'
    | '/identity/$id'
    | '/memory/$id'
    | '/memory/salvage'
    | '/memory/search'
    | '/scope/$id'
    | '/tickets/$id'
    | '/audit'
    | '/epics'
    | '/identity'
    | '/memory'
    | '/scope'
    | '/audit/criteria/$recordId'
    | '/audit/review/$recordId'
  id:
    | '__root__'
    | '/'
    | '/backlog'
    | '/profile'
    | '/audit/diff'
    | '/audit/graph'
    | '/audit/lint'
    | '/audit/verify'
    | '/identity/$id'
    | '/memory/$id'
    | '/memory/salvage'
    | '/memory/search'
    | '/scope/$id'
    | '/tickets/$id'
    | '/audit/'
    | '/epics/'
    | '/identity/'
    | '/memory/'
    | '/scope/'
    | '/audit/criteria/$recordId'
    | '/audit/review/$recordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacklogRoute: typeof BacklogRoute
  ProfileRoute: typeof ProfileRoute
  AuditDiffRoute: typeof AuditDiffRoute
  AuditGraphRoute: typeof AuditGraphRoute
  AuditLintRoute: typeof AuditLintRoute
  AuditVerifyRoute: typeof AuditVerifyRoute
  IdentityIdRoute: typeof IdentityIdRoute
  MemoryIdRoute: typeof MemoryIdRoute
  MemorySalvageRoute: typeof MemorySalvageRoute
  MemorySearchRoute: typeof MemorySearchRoute
  ScopeIdRoute: typeof ScopeIdRoute
  TicketsIdRoute: typeof TicketsIdRoute
  AuditIndexRoute: typeof AuditIndexRoute
  EpicsIndexRoute: typeof EpicsIndexRoute
  IdentityIndexRoute: typeof IdentityIndexRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
  ScopeIndexRoute: typeof ScopeIndexRoute
  AuditCriteriaRecordIdRoute: typeof AuditCriteriaRecordIdRoute
  AuditReviewRecordIdRoute: typeof AuditReviewRecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope/': {
      id: '/scope/'
      path: '/scope'
      fullPath: '/scope/'
      preLoaderRoute: typeof ScopeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/': {
      id: '/memory/'
      path: '/memory'
      fullPath: '/memory/'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/': {
      id: '/identity/'
      path: '/identity'
      fullPath: '/identity/'
      preLoaderRoute: typeof IdentityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epics/': {
      id: '/epics/'
      path: '/epics'
      fullPath: '/epics/'
      preLoaderRoute: typeof EpicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope/$id': {
      id: '/scope/$id'
      path: '/scope/$id'
      fullPath: '/scope/$id'
      preLoaderRoute: typeof ScopeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/search': {
      id: '/memory/search'
      path: '/memory/search'
      fullPath: '/memory/search'
      preLoaderRoute: typeof MemorySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/salvage': {
      id: '/memory/salvage'
      path: '/memory/salvage'
      fullPath: '/memory/salvage'
      preLoaderRoute: typeof MemorySalvageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/$id': {
      id: '/memory/$id'
      path: '/memory/$id'
      fullPath: '/memory/$id'
      preLoaderRoute: typeof MemoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/$id': {
      id: '/identity/$id'
      path: '/identity/$id'
      fullPath: '/identity/$id'
      preLoaderRoute: typeof IdentityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/verify': {
      id: '/audit/verify'
      path: '/audit/verify'
      fullPath: '/audit/verify'
      preLoaderRoute: typeof AuditVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/lint': {
      id: '/audit/lint'
      path: '/audit/lint'
      fullPath: '/audit/lint'
      preLoaderRoute: typeof AuditLintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/graph': {
      id: '/audit/graph'
      path: '/audit/graph'
      fullPath: '/audit/graph'
      preLoaderRoute: typeof AuditGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/diff': {
      id: '/audit/diff'
      path: '/audit/diff'
      fullPath: '/audit/diff'
      preLoaderRoute: typeof AuditDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/review/$recordId': {
      id: '/audit/review/$recordId'
      path: '/audit/review/$recordId'
      fullPath: '/audit/review/$recordId'
      preLoaderRoute: typeof AuditReviewRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/criteria/$recordId': {
      id: '/audit/criteria/$recordId'
      path: '/audit/criteria/$recordId'
      fullPath: '/audit/criteria/$recordId'
      preLoaderRoute: typeof AuditCriteriaRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacklogRoute: BacklogRoute,
  ProfileRoute: ProfileRoute,
  AuditDiffRoute: AuditDiffRoute,
  AuditGraphRoute: AuditGraphRoute,
  AuditLintRoute: AuditLintRoute,
  AuditVerifyRoute: AuditVerifyRoute,
  IdentityIdRoute: IdentityIdRoute,
  MemoryIdRoute: MemoryIdRoute,
  MemorySalvageRoute: MemorySalvageRoute,
  MemorySearchRoute: MemorySearchRoute,
  ScopeIdRoute: ScopeIdRoute,
  TicketsIdRoute: TicketsIdRoute,
  AuditIndexRoute: AuditIndexRoute,
  EpicsIndexRoute: EpicsIndexRoute,
  IdentityIndexRoute: IdentityIndexRoute,
  MemoryIndexRoute: MemoryIndexRoute,
  ScopeIndexRoute: ScopeIndexRoute,
  AuditCriteriaRecordIdRoute: AuditCriteriaRecordIdRoute,
  AuditReviewRecordIdRoute: AuditReviewRecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
